import React, { useState } from "react";
import { useQuery } from "wasp/client/operations";
import { getServices, getShopInfo, sendBookingOTP, createAppointment } from "wasp/client/operations";
import { BookingSteps } from "../components/booking/BookingSteps";
import { SlotPicker } from "../components/booking/SlotPicker";
import { Scissors, User, Phone, Calendar, QrCode, ShieldCheck, CheckCircle2, AlertCircle, ArrowRight, ArrowLeft, Sparkles } from "lucide-react";

const STEPS = ["Details", "Service", "Time", "Payment", "Verify & Book"];
const back = "px-4 py-3 border border-white/10 hover:bg-white/5 text-neutral-300 rounded-xl text-sm font-semibold flex items-center gap-1.5 transition-all";
const next = "flex-1 py-3 bg-amber-500 hover:bg-amber-400 active:scale-95 disabled:opacity-40 text-neutral-950 font-bold rounded-xl transition-all duration-200 shadow-lg shadow-amber-500/20 flex items-center justify-center gap-2 text-sm";
const selected = "p-4 border border-amber-500 rounded-xl cursor-pointer transition-all duration-200 flex items-center justify-between bg-amber-500/8 ring-1 ring-amber-500/30 shadow-[0_0_0_1px_hsl(38_96%_50%/0.2)]";
const unselected = "p-4 border border-white/8 rounded-xl cursor-pointer transition-all duration-200 flex items-center justify-between bg-neutral-950 hover:border-amber-500/30 hover:bg-amber-500/3";

export function BookAppointmentPage() {
 const [currentStep, setCurrentStep] = useState<number>(1);
 const [customerName, setCustomerName] = useState(""); const [customerPhone, setCustomerPhone] = useState("");
 const [selectedServiceId, setSelectedServiceId] = useState<number | null>(null);
 const [selectedDate, setSelectedDate] = useState(() => { const d = new Date(); return d.getFullYear() + "-" + String(d.getMonth()+1).padStart(2,"0") + "-" + String(d.getDate()).padStart(2,"0"); });
 const [selectedSlot, setSelectedSlot] = useState(""); const [paymentMethod, setPaymentMethod] = useState<"PAY_NOW" | "PAY_AT_SHOP">("PAY_NOW");
 const [paymentProof, setPaymentProof] = useState(""); const [otpCode, setOtpCode] = useState("");
 const [isSendingOtp, setIsSendingOtp] = useState(false); const [isSubmitting, setIsSubmitting] = useState(false); const [otpSent, setOtpSent] = useState(false);
 const [errorMessage, setErrorMessage] = useState<string | null>(null); const [bookingSuccess, setBookingSuccess] = useState<any | null>(null); const [upiCopied, setUpiCopied] = useState(false);
 const { data: services, isLoading: servicesLoading } = useQuery(getServices); const { data: shopInfo } = useQuery(getShopInfo);
 const selectedService = services?.find((s) => s.id === selectedServiceId);
 const formatINR = (paise: number) => new Intl.NumberFormat("en-IN", { style:"currency", currency:"INR", maximumFractionDigits:0 }).format(paise / 100);
 const handleNextFromStep1 = (e: React.FormEvent) => { e.preventDefault(); setErrorMessage(null); if (!customerName.trim()) return setErrorMessage("Please enter your name."); if (customerPhone.replace(/\D/g, "").length < 10) return setErrorMessage("Please enter a valid 10-digit mobile number."); setCurrentStep(2); };
 const handleSendOtp = async () => { setErrorMessage(null); setIsSendingOtp(true); try { await sendBookingOTP({ phone: customerPhone }); setOtpSent(true); } catch (err:any) { setErrorMessage(err.message || "Failed to send OTP. Please try again."); } finally { setIsSendingOtp(false); } };
 const handleFinalSubmit = async (e: React.FormEvent) => { e.preventDefault(); setErrorMessage(null); if (!selectedServiceId || !selectedDate || !selectedSlot) return setErrorMessage("Missing booking details. Please review your selection."); if (!otpCode || otpCode.length < 4) return setErrorMessage("Please enter the OTP sent to your mobile number."); setIsSubmitting(true); try { const appointment = await createAppointment({ customerName, customerPhone, serviceId:selectedServiceId, date:selectedDate, startTime:selectedSlot, paymentMethod, paymentProof:paymentMethod === "PAY_NOW" ? paymentProof : undefined, otpCode }); setBookingSuccess(appointment); } catch (err:any) { setErrorMessage(err.message || "Failed to complete appointment booking."); } finally { setIsSubmitting(false); } };
 if (bookingSuccess) return <div className="min-h-screen bg-neutral-950 text-white flex items-center justify-center p-4"><div className="max-w-md w-full bg-neutral-900/80 border border-white/8 rounded-2xl p-6 sm:p-8 backdrop-blur-xl shadow-2xl space-y-6 text-center animate-[fade-up_0.4s_cubic-bezier(0.16,1,0.3,1)_both]"><div className="relative w-20 h-20 mx-auto"><div className="w-20 h-20 bg-emerald-500/15 border-2 border-emerald-500/40 rounded-full flex items-center justify-center animate-[scale-in_0.5s_cubic-bezier(0.16,1,0.3,1)_0.1s_both]"><svg className="w-10 h-10 text-emerald-400" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2.5" strokeLinecap="round" strokeLinejoin="round"><path d="M5 13l4 4L19 7" strokeDasharray="100" strokeDashoffset="0" style={{animation:"draw-check 0.6s ease-out 0.4s both"}} /></svg></div><div className="absolute inset-0 rounded-full bg-emerald-500/10 blur-xl scale-150 animate-pulse" /></div><div className="space-y-2"><h2 className="text-2xl font-black tracking-tight">Appointment Confirmed!</h2><p className="text-sm text-neutral-400">We look forward to styling you. A confirmation SMS has been dispatched.</p></div><Summary appointment={bookingSuccess} /><a href="/" className="inline-flex items-center justify-center w-full px-6 py-3 bg-amber-500 hover:bg-amber-400 text-neutral-950 font-bold rounded-xl transition-all shadow-lg shadow-amber-500/20 active:scale-95">Back to Home</a></div></div>;
 const nav = (onBack:()=>void, onNext:()=>void, label:string, disabled=false) => <div className="flex items-center gap-3 pt-2"><button type="button" onClick={onBack} className={back}><ArrowLeft className="w-4 h-4" /> Back</button><button type="button" disabled={disabled} onClick={onNext} className={next}>{label}<ArrowRight className="w-4 h-4" /></button></div>;
 return <div className="min-h-screen bg-neutral-950 text-neutral-100 flex flex-col justify-between"><header className="border-b border-white/8 bg-neutral-900/50 backdrop-blur-md sticky top-0 z-50"><div className="max-w-3xl mx-auto px-4 h-16 flex items-center justify-between"><a href="/" className="flex items-center gap-2 font-bold text-lg text-white"><Scissors className="w-5 h-5 text-amber-500" />BSAM</a><span className="text-xs bg-amber-500/10 text-amber-400 border border-amber-500/20 px-2.5 py-1 rounded-full font-medium flex items-center gap-1"><Sparkles className="w-3 h-3" /> Quick Booking</span></div></header><main className="flex-1 max-w-2xl w-full mx-auto px-4 py-8 space-y-6"><BookingSteps currentStep={currentStep} steps={STEPS} />{errorMessage && <div className="p-4 bg-rose-500/10 border border-rose-500/25 text-rose-300 rounded-xl text-sm flex items-start gap-3"><AlertCircle className="w-5 h-5 text-rose-400 shrink-0 mt-0.5" />{errorMessage}</div>}<div key={currentStep} className="bg-neutral-900/80 border border-white/8 rounded-2xl p-6 sm:p-8 backdrop-blur-xl shadow-xl shadow-black/30 animate-[step-slide-in_0.35s_cubic-bezier(0.16,1,0.3,1)_both]">
 {currentStep===1 && <form onSubmit={handleNextFromStep1} className="space-y-6"><Title icon={<User />} title="Customer Details" text="No account registration needed. Just your name and mobile number." /><Field label="Full Name" icon={<User />} inputProps={{type:"text",placeholder:"e.g. Rahul Sharma",value:customerName,onChange:e=>setCustomerName(e.target.value),required:true}} /><Field label="Mobile Number (India)" icon={<Phone />} inputProps={{type:"tel",placeholder:"e.g. 9876543210",value:customerPhone,onChange:e=>setCustomerPhone(e.target.value),required:true}} /><button type="submit" className={"w-full "+next}>Continue to Select Service<ArrowRight className="w-4 h-4" /></button></form>}
 {currentStep===2 && <div className="space-y-6"><Title icon={<Scissors />} title="Select Service" text="Choose the grooming treatment you require." />{servicesLoading ? <div className="space-y-3">{[1,2,3].map(i=><div key={i} className="h-20 bg-neutral-950/50 animate-pulse rounded-xl" />)}</div> : services?.length ? <div className="grid gap-3">{services.map(service=><div key={service.id} onClick={()=>setSelectedServiceId(service.id)} className={selectedServiceId===service.id?selected:unselected}><div><h3 className="font-semibold text-white">{service.name}</h3>{service.description && <p className="text-xs text-neutral-400">{service.description}</p>}<p className="text-xs text-amber-400 mt-1">Duration: {service.durationMinutes} mins</p></div><div className="text-right"><b className="text-white">{formatINR(service.price)}</b><p className="text-[11px] text-neutral-400">Token: {formatINR(service.tokenAmount)}</p></div></div>)}</div> : <p className="text-sm text-neutral-400">No services currently listed.</p>}{nav(()=>setCurrentStep(1),()=>setCurrentStep(3),"Select Time Slot",!selectedServiceId)}</div>}
 {currentStep===3 && <div className="space-y-6"><Title icon={<Calendar />} title="Choose Date & Slot" text={"Pick an open appointment time for " + selectedService?.name + "."} />{selectedServiceId && <SlotPicker date={selectedDate} setDate={setSelectedDate} selectedSlot={selectedSlot} setSelectedSlot={setSelectedSlot} serviceId={selectedServiceId} />}{nav(()=>setCurrentStep(2),()=>setCurrentStep(4),"Proceed to Payment",!selectedSlot)}</div>}
 {currentStep===4 && <div className="space-y-6"><Title icon={<QrCode />} title="Payment Option" text="Pay token money via UPI QR to lock your slot, or pay directly at shop." /><div className="grid grid-cols-2 gap-3"><PayCard active={paymentMethod==="PAY_NOW"} onClick={()=>setPaymentMethod("PAY_NOW")} title="Pay Token via UPI" sub={(selectedService?formatINR(selectedService.tokenAmount):"₹50")+" Token"} text="Scan UPI QR & confirm" /><PayCard active={paymentMethod==="PAY_AT_SHOP"} onClick={()=>setPaymentMethod("PAY_AT_SHOP")} title="Pay at Shop" sub="Full Price" text="Pay when you arrive" /></div>{paymentMethod==="PAY_NOW" && <div className="bg-neutral-950/80 border border-white/8 rounded-xl p-5 space-y-4 text-center"><p className="text-xs text-neutral-400 font-medium">Scan with any UPI App — GPay, PhonePe, Paytm</p><div className="relative inline-block"><div className="bg-white p-3 rounded-xl mx-auto shadow-md qr-glow-ring"><img src={"https://api.qrserver.com/v1/create-qr-code/?size=200x200&data="+encodeURIComponent("upi://pay?pa="+encodeURIComponent(shopInfo?.phone||"barbershop@upi")+"&pn="+encodeURIComponent(shopInfo?.shopName||"BSAM Barber Shop")+"&am="+((selectedService?.tokenAmount||5000)/100).toFixed(2)+"&cu=INR")} alt="UPI QR Code" className="w-44 h-44 object-contain mx-auto block" /></div></div><button type="button" onClick={async()=>{try { await navigator.clipboard.writeText(shopInfo?.phone||"barbershop@upi"); setUpiCopied(true); window.setTimeout(()=>setUpiCopied(false), 1800); } catch { setErrorMessage("Could not copy the UPI ID. Please copy it manually."); }}} className="inline-flex items-center gap-2 text-xs text-amber-400 border border-amber-500/25 bg-amber-500/8 px-3 py-1.5 rounded-full hover:bg-amber-500/15 transition-all font-medium">{upiCopied ? "UPI ID copied" : "Copy UPI ID"}</button><div className="text-left"><label className="text-xs font-semibold text-neutral-400 uppercase tracking-wider block">UPI Ref / UTR No. (Optional)</label><input type="text" placeholder="e.g. 329104810294" value={paymentProof} onChange={e=>setPaymentProof(e.target.value)} className="w-full mt-1 px-3 py-2.5 bg-neutral-900 border border-white/10 rounded-xl text-white text-sm placeholder:text-neutral-600 focus:outline-none focus:ring-2 focus:ring-amber-500/40 focus:border-amber-500/60" /></div></div>}{nav(()=>setCurrentStep(3),()=>{setCurrentStep(5);handleSendOtp();},"Verify Mobile & Confirm")}</div>}
 {currentStep===5 && <form onSubmit={handleFinalSubmit} className="space-y-6"><Title icon={<ShieldCheck />} title="Enter OTP Code" text="We sent a 6-digit OTP code to your mobile number." /><div className="space-y-3"><label className="text-xs font-semibold text-neutral-400 uppercase tracking-wider">6-Digit OTP</label><div className="flex gap-2 justify-center">{Array.from({length:6}).map((_,i)=><input key={i} type="text" inputMode="numeric" maxLength={1} value={otpCode[i]||""} onChange={e=>{const val=e.target.value.replace(/\D/g,"");const arr=otpCode.split("");arr[i]=val;setOtpCode(arr.join("").slice(0,6));if(val&&i<5)(e.target.parentElement?.children[i+1] as HTMLInputElement)?.focus();}} onKeyDown={e=>{if(e.key==="Backspace"&&!otpCode[i]&&i>0)((e.target as HTMLInputElement).parentElement?.children[i-1] as HTMLInputElement)?.focus();}} className={"w-11 text-center text-xl font-bold rounded-xl border-2 bg-neutral-950 text-amber-400 focus:outline-none transition-all "+(otpCode[i]?"border-amber-500 shadow-[0_0_0_3px_hsl(38_96%_50%/0.15)]":"border-white/10 focus:border-amber-500/60 focus:ring-2 focus:ring-amber-500/20")} style={{height:"3.25rem"}} />)}</div><div className="flex justify-between text-xs text-neutral-400"><span>{otpSent?"Didn't receive code?":"Sending your code..."}</span><button type="button" disabled={isSendingOtp} onClick={handleSendOtp} className="text-amber-400 hover:underline">{isSendingOtp?"Resending...":"Resend OTP"}</button></div></div><div className="bg-neutral-950 border border-white/8 rounded-xl p-4 text-xs space-y-2"><b>Booking Summary</b><p className="text-neutral-400">{selectedService?.name} · <span className="text-amber-400">{selectedDate} at {selectedSlot}</span></p><p className="text-neutral-400">{paymentMethod==="PAY_NOW"?"UPI Token":"Pay at Shop"}</p></div><div className="flex gap-3"><button type="button" onClick={()=>setCurrentStep(4)} className={back}><ArrowLeft className="w-4 h-4" /> Back</button><button type="submit" disabled={isSubmitting||!otpCode} className="flex-1 py-3 bg-emerald-500 hover:bg-emerald-400 active:scale-95 disabled:opacity-40 text-neutral-950 font-bold rounded-xl transition-all shadow-lg shadow-emerald-500/20 flex items-center justify-center gap-2 text-sm">{isSubmitting?"Confirming...":<><CheckCircle2 className="w-4 h-4" /> Confirm & Book Appointment</>}</button></div></form>}
 </div></main><footer className="border-t border-white/8 py-4 text-center text-xs text-neutral-500">© {new Date().getFullYear()} BSAM. Barber Shop Appointment Manager.</footer></div>;
}
function Title({icon,title,text}:{icon:React.ReactNode;title:string;text:string}) { return <div><h2 className="text-xl font-bold text-white flex items-center gap-2"><span className="text-amber-500">{icon}</span>{title}</h2><p className="text-sm text-neutral-400 mt-1">{text}</p></div>; }
function Field({label,icon,inputProps}:{label:string;icon:React.ReactNode;inputProps:React.InputHTMLAttributes<HTMLInputElement>}) { return <div className="space-y-2"><label className="text-xs font-semibold text-neutral-400 uppercase tracking-wider">{label}</label><div className="relative"><span className="absolute left-3 top-3.5 text-neutral-500 w-4 h-4">{icon}</span><input {...inputProps} className="w-full pl-10 pr-4 py-2.5 bg-neutral-950 border border-white/10 rounded-xl text-white placeholder:text-neutral-600 focus:outline-none focus:ring-2 focus:ring-amber-500/40 focus:border-amber-500/60 transition-all text-sm" /></div></div>; }
function PayCard({active,onClick,title,sub,text}:{active:boolean;onClick:()=>void;title:string;sub:string;text:string}) { return <button type="button" onClick={onClick} className={(active?selected:unselected)+" text-left"}><div><b className="text-sm text-white">{title}</b><p className="text-xs text-amber-400 mt-1">{sub}</p><p className="text-[11px] text-neutral-400 mt-1">{text}</p></div></button>; }
function Summary({appointment}:{appointment:any}) { return <div className="bg-neutral-950/60 border border-white/8 rounded-xl p-4 text-left space-y-3 text-sm"><div className="flex justify-between py-1.5 border-b border-white/5"><span className="text-neutral-400">Customer</span><b>{appointment.customerName}</b></div><div className="flex justify-between py-1.5 border-b border-white/5"><span className="text-neutral-400">Service</span><b>{appointment.service?.name}</b></div><div className="flex justify-between py-1.5 border-b border-white/5"><span className="text-neutral-400">Date & Time</span><b className="text-emerald-400">{appointment.date?new Date(appointment.date).toLocaleDateString("en-IN"):""} at {appointment.startTime}</b></div><div className="flex justify-between py-1.5"><span className="text-neutral-400">Payment</span><span>{appointment.paymentMethod==="PAY_NOW"?"UPI Token Paid":"Pay at Shop"}</span></div></div>; }
export default BookAppointmentPage;
